from graph.graph import build_graph

graph = build_graph()

result = graph.invoke(
    {
        "question": "Who are you? give me answers in english only",
        "answer": ""
    }
)

print("\nFinal State:")
print(result)

# steps :
# 1 - build_graph() will run and start the graph execution with the initial state provided in graph.invoke()
#     and it'll call the chatbot_node with the initial state.
# 2 - chatbot_node will read the question from the state, call the Ollama service to get the answer, and return 
#     the updated state with the answer.
# 3 - The final state will be printed, which will include the original question and the answer generated by 
#     the chatbot_node.
# 

